### ISSUE TITLE
Include task numbers in output

### ISSUE THREAD

**Issue by earcanal** [fniessink/next-action#712]
I'd like to see task numbers in the output so that I can refer to them in a subsequent command (notably to start time tracking the next action using the `punch` addon). I don't see an option to do this.

**Comment by fniessink** [comment]
Next-action 1.13.0 has line numbers. Upgrade with:

 ```console
$ pip install -U next-action
Collecting next-action
...
```
Show line numbers like this:

```console
$ next-action --line-number
(A) Call mom [4]
$ next-action --line-number --reference always
(A) Call mom [/home/frank/todo.txt:4]
```

See the [README](https://github.com/fniessink/next-action/blob/master/README.md) for more info.

Enjoy!
